import json, random
def _ph(): return f"+1404555{random.randint(1000,9999)}"
def _bid(): return f"HAS-{random.randint(1000,9999)}"
PATTERNS = {
    "reminder": {"triggers": ["reminder","day before","confirm appointment","tomorrow"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Hi {c.get('customer','there')}! Help Assembly Services LLC reminder: your {c.get('item','furniture')} assembly is {c.get('date','tomorrow')} at {c.get('time','10:00 AM')}. Reply with questions!"},"reason":"Send reminder"}]}},
    "send_quote": {"triggers": ["send quote","text quote","quote to","send estimate"], "gen": lambda c: {"actions": [{"tool":"create_quote","params":{"customer":c.get("customer","Customer"),"items":[c.get("item","furniture")],"prices":[c.get("price",150)],"valid_until":"7 days"},"reason":"Quote"},{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Hi {c.get('customer','there')}! Quote for {c.get('item','furniture')} from Help Assembly Services LLC: ${c.get('price',150)}. Valid 7 days. Reply YES to book!"},"reason":"Send quote"}]}},
    "thank_you": {"triggers": ["thank you","thanks","appreciation"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Thanks for choosing Help Assembly Services LLC! We hope your {c.get('item','furniture')} looks great. We'd love a Google review!"},"reason":"Thank you"}]}},
    "review": {"triggers": ["review","feedback","rate us","google review"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Would you mind a quick Google review? https://g.page/helpassembly/review — Help Assembly Services LLC thanks you!"},"reason":"Review request"}]}},
    "follow_up": {"triggers": ["follow up","check in","how was","how is everything"], "gen": lambda c: {"actions": [{"tool":"send_follow_up","params":{"customer":c.get("customer","Customer"),"type":"post_service","message":f"Hi {c.get('customer','there')}! Just checking in from Help Assembly Services LLC — how's the {c.get('item','furniture')}?"},"reason":"Follow up"}]}},
    "complaint": {"triggers": ["complaint","wobbles","broken","damaged","not right","issue"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"We're sorry about the issue with your {c.get('item','furniture')}. Covered under our 90-day warranty. Scheduling a free fix. Help Assembly Services LLC will contact you."},"reason":"Complaint response"}]}},
    "book": {"triggers": ["book","schedule","appointment","set up a time","come out"], "gen": lambda c: {"actions": [{"tool":"check_availability","params":{"date":c.get("date","next available"),"service_area":c.get("city","Atlanta")},"reason":"Check slots"},{"tool":"create_booking","params":{"customer":c.get("customer","Customer"),"service":c.get("item","furniture"),"date":c.get("date","TBD"),"time":c.get("time","TBD"),"technician":"TBD"},"reason":"Book"},{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Booked! Your {c.get('item','assembly')} is {c.get('date','TBD')} at {c.get('time','TBD')}. — Help Assembly Services LLC"},"reason":"Confirm"}]}},
    "reschedule": {"triggers": ["reschedule","change date","move appointment"], "gen": lambda c: {"actions": [{"tool":"reschedule_booking","params":{"booking_id":_bid(),"new_date":c.get("new_date","TBD"),"new_time":c.get("new_time","TBD")},"reason":"Reschedule"},{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Rescheduled to {c.get('new_date','TBD')} at {c.get('new_time','TBD')}. — Help Assembly Services LLC"},"reason":"Confirm"}]}},
    "cancel": {"triggers": ["cancel","no longer need"], "gen": lambda c: {"actions": [{"tool":"cancel_booking","params":{"booking_id":_bid(),"reason":"Customer request"},"reason":"Cancel"},{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":"Cancelled. We're here if you need us! — Help Assembly Services LLC"},"reason":"Confirm"}]}},
    "dispatch": {"triggers": ["dispatch","send technician","tech on the way"], "gen": lambda c: {"actions": [{"tool":"dispatch_technician","params":{"technician_id":c.get("technician","Marcus"),"address":f"{random.randint(100,9999)} Main St, {c.get('city','Atlanta')}, GA","eta":c.get("eta","25 min")},"reason":"Dispatch"},{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"{c.get('technician','Technician')} on the way! ETA: {c.get('eta','25 min')}. — Help Assembly Services LLC"},"reason":"Notify"}]}},
    "eta_update": {"triggers": ["eta","running late","delayed"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Update: {c.get('technician','Technician')} running {c.get('delay','15 min')} behind. New ETA: {c.get('new_eta','shortly')}. Sorry! — Help Assembly Services LLC"},"reason":"ETA update"}]}},
    "job_complete": {"triggers": ["job complete","finished","done with","completed","all done"], "gen": lambda c: {"actions": [{"tool":"log_job_complete","params":{"booking_id":_bid(),"actual_hours":c.get("hours",2),"notes":"Complete"},"reason":"Log"},{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Your {c.get('item','furniture')} assembly is complete! Invoice coming. — Help Assembly Services LLC"},"reason":"Notify"},{"tool":"a2a_send","params":{"target_agent":"billing","message":f"Generate invoice for {_bid()}","priority":"normal"},"reason":"Trigger billing"}]}},
    "invoice": {"triggers": ["invoice","bill","charge","payment"], "gen": lambda c: {"actions": [{"tool":"create_invoice","params":{"booking_id":_bid(),"amount":c.get("price",150),"items":[c.get("item","furniture")]},"reason":"Invoice"},{"tool":"send_invoice","params":{"invoice_id":f"INV-{random.randint(10000,99999)}","method":"sms"},"reason":"Send"}]}},
    "schedule": {"triggers": ["schedule","calendar","today's jobs","tomorrow's jobs"], "gen": lambda c: {"actions": [{"tool":"get_schedule","params":{"date":c.get("date","today"),"technician":"all"},"reason":"Pull schedule"}]}},
    "availability": {"triggers": ["availability","open slot","next opening"], "gen": lambda c: {"actions": [{"tool":"check_availability","params":{"date":c.get("date","next available"),"service_area":c.get("city","Atlanta")},"reason":"Check"}]}},
    "weather": {"triggers": ["weather","rain","forecast","outdoor jobs"], "gen": lambda c: {"actions": [{"tool":"open_app","params":{"app_name":"Weather"},"reason":"Weather"},{"tool":"screenshot","params":{},"reason":"Capture"},{"tool":"generate_report","params":{"report_type":"weather_impact","date_range":"next_3_days"},"reason":"Report"}]}},
    "inventory": {"triggers": ["inventory","in stock","parts","hardware"], "gen": lambda c: {"actions": [{"tool":"update_inventory","params":{"item":c.get("hardware_type","cam lock screws"),"quantity":0,"action":"check"},"reason":"Check stock"},{"tool":"a2a_send","params":{"target_agent":"inventory","message":"Stock check","priority":"normal"},"reason":"Notify"}]}},
    "services": {"triggers": ["what services","what do you offer","services offered"], "gen": lambda c: {"actions": [{"tool":"respond_to_customer","params":{"customer":c.get("customer","Customer"),"channel":"sms","message":"Help Assembly Services LLC: Standard ($75-250), Premium ($200-600), Outdoor ($150-500), Commercial ($300-1500). Serving Metro Atlanta!"},"reason":"Info"}]}},
    "coverage": {"triggers": ["service area","where do you","do you serve","coverage"], "gen": lambda c: {"actions": [{"tool":"respond_to_customer","params":{"customer":c.get("customer","Customer"),"channel":"sms","message":"Help Assembly Services LLC serves Metro Atlanta: Atlanta, Marietta, Decatur, Alpharetta, Sandy Springs, Roswell, Johns Creek, and more!"},"reason":"Coverage info"}]}},
    "pricing": {"triggers": ["how much","pricing","cost","rates"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"For {c.get('item','furniture assembly')}, our range is $75-$250. Send us a photo for a precise quote! — Help Assembly Services LLC"},"reason":"Pricing"}]}},
    "warranty": {"triggers": ["warranty","guarantee","covered"], "gen": lambda c: {"actions": [{"tool":"respond_to_customer","params":{"customer":c.get("customer","Customer"),"channel":"sms","message":"All work by Help Assembly Services LLC includes a 90-day workmanship warranty. We fix it free if anything isn't right!"},"reason":"Warranty info"}]}},
    "referral": {"triggers": ["referral","refer a friend","referral code"], "gen": lambda c: {"actions": [{"tool":"send_sms","params":{"number":c.get("phone",_ph()),"message":f"Share Help Assembly Services LLC — you BOTH get $25 off! Code: REF{random.randint(1000,9999)}"},"reason":"Referral"}]}},
}
def match_pattern(query, threshold=0.75):
    ql = query.lower(); best = None; best_s = 0.0
    for name, p in PATTERNS.items():
        for t in p["triggers"]:
            score = 1.0 if t in ql else (len(set(ql.split()) & set(t.split())) / max(len(set(t.split())), 1)) * 0.8
            if score > best_s: best_s = score; best = name
    return (best, best_s) if best and best_s >= threshold else None
def generate_from_pattern(name, ctx): return PATTERNS[name]["gen"](ctx)
def list_patterns(): return [{"name": n, "triggers": p["triggers"]} for n, p in PATTERNS.items()]
